# Generated by Django 5.1.4 on 2025-03-01 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_post_shared_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='shared_by',
        ),
        migrations.AddField(
            model_name='post',
            name='shared_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_posts', to='api.post'),
        ),
    ]
