# Generated by Django 5.1.4 on 2025-03-01 06:07

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_post_shared_by_post_shared_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.profile_picture_upload),
        ),
    ]
